[project]
name = "band-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyautogui>=0.9.54",
    "selenium>=4.27.1",
    "webdriver-manager>=4.0.2",
]
